version: "3"
services:
    myapp:
        build: .
        image: release:1.0
        ports:
            - 8082:3000
        networks:
            - release-compose-network
        cap_drop:
            - NET_ADMIN
            - SYS_ADMIN
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
                reservations:
                    cpus: '0.60'
                    memory: 1024M

networks: 
  release-compose-network:
    driver: bridge